### PR TITLE
Upgrade to webpack2 & FIX #20

### LINKED ISSUE #20: Error: Chunk.entry was removed. Use hasRuntime()
The latest webpack release (2.1.0-beta.17) raises the following error:

```
node_modules/webpack/lib/Chunk.js:34
        throw new Error("Chunk.entry was removed. Use hasRuntime()");
        ^

Error: Chunk.entry was removed. Use hasRuntime()
    at Chunk.Object.defineProperty.get (node_modules/webpack/lib/Chunk.js:34:9)
    at node_modules/webpack-split-by-path/index.js:91:23
    at Array.filter (native)
    at Compilation.<anonymous> (node_modules/webpack-split-by-path/index.js:89:10)
    at Compilation.applyPluginsBailResult (node_modules/webpack/node_modules/tapable/lib/Tapable.js:52:27)
    at Compilation.seal (node_modules/webpack/lib/Compilation.js:543:8)
    at Compiler.<anonymous> (node_modules/webpack/lib/Compiler.js:436:15)
    at node_modules/webpack/node_modules/tapable/lib/Tapable.js:152:11
    at Compilation.<anonymous> (node_modules/webpack/lib/Compilation.js:434:10)
    at node_modules/webpack/lib/Compilation.js:410:12
    at node_modules/webpack/lib/Compilation.js:325:10
    at node_modules/async/lib/async.js:52:16
    at done (node_modules/async/lib/async.js:246:17)
    at node_modules/async/lib/async.js:44:16
    at node_modules/webpack/lib/Compilation.js:325:10
    at node_modules/async/lib/async.js:52:16
```

Seems to be related to [index.js:91](https://github.com/BohdanTkachenko/webpack-split-by-path/blob/master/index.js#L91)

Also see this related issue on the webpack repo: https://github.com/webpack/webpack/issues/2764

And this commit to the extract-text plugin for a similar problem may be of help: https://github.com/webpack/extract-text-webpack-plugin/commit/ba0a71dcc72dd298f602f96906e2042a08cbe039

### PR DESCRIPTION
**Pull request by ndelangen**
Upgrade to webpack 2.1.x-beta.20, 
FIX compatibility with webpack 2.x ( #20 )

Upgrade other dependencies to latest.

Let me know if you want me to change anything or PR to a different branch?
Full disclosure: this is my first contribution to a webpack plugin.

### CODE REVIEW

**Comment by BohdanTkachenko** [comment]
Thanks for your PR! I think that I need to make some separate branch and publish this as some beta version while webpack2 is in beta too.

**Comment by micaelmbagira** [comment]
👍 Looks good, when do you plan to merge/release @BohdanTkachenko ?

**Comment by BohdanTkachenko** [comment]
@micaelmbagira I'll take a closer look on this weekend - don't have much time during work week

**Comment by the-spyke** [comment]
Works for me. Thanks, @ndelangen.

**Comment by BohdanTkachenko** [comment]
Published 0.1.0-beta.1 to NPM
Git branch webpack2-beta

Will merge it to master once webpack2 will be stable

**Comment by BohdanTkachenko** [comment]
Webpack issue to track when webpack2 is released - https://github.com/webpack/webpack/issues/1545

Also, will keep this PR open to be not forget about it

**Comment by micaelmbagira** [comment]
Great, thanks! Still, I have this issue now `Uncaught TypeError: Cannot read property 'call' of undefined`... caused by `modules[moduleId]` undefined, coming from the `manifest.js`. Maybe it is related to https://github.com/BohdanTkachenko/webpack-split-by-path/pull/17 ?

**Comment by jameswyse** [comment]
Just upgraded to `0.1.0-beta.1` and I'm now getting the same error as @micaelmbagira above. 

I have a hunch this is related to `html-webpack-plugin` which doesn't seem to be aware of the vendor chunk I specified with this plugin. I tried the `chunksSortMode: 'dependency'` option but it didn't seem to help.

I'm on a tight deadline at the moment so I've had to disable this plugin for now. Will investigate some more when I have time! :smile:

**Comment by hekike** [comment]
Webpack 2.x final release is out in the meantime: https://medium.com/webpack/webpack-2-2-the-final-release-76c3d43bf144

Any plan to re-visit this issue?

**Comment by ndelangen** [comment]
I resolved the conflicts and updated to the latest webpack version `2.2.0`

**Comment by hekike** [comment]
@ndelangen hmm I tried it out with our app but I got this:

```
bootstrap 319608a…:52 Uncaught TypeError: Cannot read property 'call' of undefined
```

```
// Execute the module function
modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
```

**Comment by ndelangen** [comment]
@hekike Looks like a module is missing, `modules[moduleId]` is returning `undefined`.

Try finding which module is missing, and trace for clues why it's missing, might be a loader that's mis-configured?

What exactly have you tried?

**Comment by hekike** [comment]
@ndelangen thanks, but it works without `webpack-split-by-path` (I use your branch).

**Comment by ndelangen** [comment]
It worked before this: https://github.com/BohdanTkachenko/webpack-split-by-path/pull/22/commits/0bac59187fdeebe5e162ae62d4aeb26cc839e66c ?

**Comment by hekike** [comment]
@ndelangen no, same error message :/

**Comment by hekike** [comment]
Did someone else receive similar error message?

**Comment by hekike** [comment]
@ndelangen okay, I realized what's happening. It splits the bundle correctly, I've all of the chunks, in my output folder, but my `index.html` only contains the original one, and doesn't include the other chunks. I use `HtmlWebpackPlugin` to put `<script>` tags to my index.html.

Do you have an idea from this angle? Is it more like a `webpack-split-by-path`  or a `html-webpack-plugin` issue?

**Update:**

I debugged the `html-webpack-plugin` and seems to be that the splitted chunks in the `compiler.plugin("emit", function(compilation, callback) {...}` has `initial: false,` value, and that's why they are skipped.

```
{
    id: 0,
    rendered: true,
    initial: false,
    entry: false,
    recorded: undefined,
    extraAsync: false,
    size: 7469113,
    names: [ 'vendors' ],
    files: [ 'script/vendors.js', 'script/vendors.js.map' ],
    hash: '4455dd89e114f652e0f9',
    parents: [ 2 ],
    origins: []
}
```

As I see `isInitial()` is determinated based on entrypoints: https://github.com/webpack/webpack/blob/028c51301733836abbedc88be7483af2623f5943/lib/Chunk.js#L79

Shouldn't we add chunk to the `this.entrypoints` ?

**Pull request merged**
