### PR TITLE
add a significant patch about manifest separating

### PR DESCRIPTION
**Pull request by e-cloud**
this is a big PR!
- improve the code style.
- higher cohesion and lower coupling
- add some reasonable docs
- make the example more representative
- **essential**, separate manifest info into a standalone chunk. see #7

### CODE REVIEW

**Comment by e-cloud** [comment]
@BohdanTkachenko , could you review this pr :smiley:

**Comment by BohdanTkachenko** [comment]
Wow! Looks great! Will review it.

**Comment by BohdanTkachenko** [comment]
It seems that this PR breaks html-webpack-plugin.
In my project it says `Error: The loader "/Users/bohdantkachenko/Projects/test/node_modules/html-webpack-plugin/lib/loader.js!/Users/bohdantkachenko/Projects/test/src/index.ejs" didn't return html.`

**Comment by e-cloud** [comment]
@BohdanTkachenko , could you provide some example code to test?

And, analyzing from your error above, it seems that ejs file is not converted to hml string before being passed to the html-webpack-plugin. Coud you add something like ejs-loader or so?

**Comment by BohdanTkachenko** [comment]
You can find an example here: https://github.com/BohdanTkachenko/webpack-split-by-path-error-demo-1

Also, I changed from ejs to html and it is the same. Also if you switch to master branch of webpack-split-by-path - everything works.

**Comment by e-cloud** [comment]
@BohdanTkachenko i just solved the problem with some changes. It **may break compatibility**. 

The reason that the master doesn't have problem, is that it doesn't add a chunk outside [chunk filtering logic](https://github.com/BohdanTkachenko/webpack-split-by-path/blob/master/index.js#L94-L131) which doesn't impact the child compilation with just skipping.

**Comment by e-cloud** [comment]
@BohdanTkachenko, do you have time to review?

**Comment by BohdanTkachenko** [comment]
Tested - seems to be working. Merged and published to NPM as version 0.1.0
Thanks for your awesome contribution!

**Comment by e-cloud** [comment]
it is normal that user might use multiple instance of Webpack-split-by-path? Current implementation doesn't support multiple instance as manifest is the only entry chunk that the non-first instances actually do nothing.

**Comment by BohdanTkachenko** [comment]
I don't think that it is normal because webpack-split-by-path supports several bundles in configuration, so no need in several instances of a plugin.

**Pull request merged**
